name: Test Application

on:
  pull_request:
    branches: [ "master" ]
env:
  NAMESPACE: ${{ secrets.HUB_LOGIN }}
  IMAGE_NAME: "dnstls"
  IMAGE_TAG: "test"
  TEST_PORT: "1853"

jobs:

  testing_image:
    name: Build and Test Docker Image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        
      - name: Build image
        run: "docker build -t ${{ env.IMAGE_NAME }} ."
        
      - name: Run image
        run: "docker run -d -p ${{env.TEST_PORT}}:53/udp ${{ env.IMAGE_NAME }}"
        
      - name: Check DNS over TLS
        run: "dig @localhost -p ${{env.TEST_PORT}} google.com | grep -c 'ANSWER SECTION'"
        
  testing_compose_file:
      name: Test Docker compose
      runs-on: ubuntu-20.04
      
      steps:
        - uses: actions/checkout@v3
        
        - name: Deploy Docker Compose
          run: "docker compose up -d"  
          
        - name: Check DNS over TLS
          run: "dig @localhost -p ${{env.TEST_PORT}} google.com | grep -c 'ANSWER SECTION'"
 
  push_test_image:
        needs: [testing_image, testing_compose_file]
        
        name: Push Test Image on Hub
        runs-on: ubuntu-20.04
        
        steps:
          - uses: actions/checkout@v3
      
          - name: Log in to the Container registry
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.HUB_LOGIN }}
              password: ${{ secrets.HUB_TOKEN }}
      
          - name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
              
  testing_hub_image:
        needs: [push_test_image]

        name: Testing Image from Hub
        runs-on: ubuntu-20.04

        steps:
          - uses: actions/checkout@v3
          
          - name: Run image
            run: "docker run -d -p ${{env.TEST_PORT}}:53/udp ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

          - name: Check DNS over TLS
            run: "dig @localhost -p ${{env.TEST_PORT}} google.com | grep -c 'ANSWER SECTION'"
        
      
